<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayFullClick</name>
   <tag></tag>
   <elementGuidId>2a0d2836-92ca-47fc-b300-95237cd0168e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[starts-with(@id,'payfull_')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[starts-with(@id,'payfull_')][1]</value>
   </webElementProperties>
</WebElementEntity>
