<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AccountMatchingMGA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>15850a68-35d6-4edf-b7c3-e3fc0e360b22</testSuiteGuid>
   <testCaseLink>
      <guid>af6464d4-4428-424f-a656-ab72fbb39caf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01-LoginApplication</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d7b8ce22-d3f6-4bd3-b492-8aee9e65d66a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04-AccountMatching-MGA</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4d7b4438-0e08-49aa-8b66-bb7ac22dc99c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/MTA_PolicyNO</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4d7b4438-0e08-49aa-8b66-bb7ac22dc99c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PolicyNo</value>
         <variableId>7aa213af-01dc-4774-96b7-8e9d7c39244b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>952df2ad-ec4c-4db0-8918-5c2e7d363865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9805e1c8-674b-4c46-b8a2-f194b59f51d1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
