<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AllAccountMatching</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>680cc29d-f923-41fd-a423-441ec24a7da5</testSuiteGuid>
   <testCaseLink>
      <guid>10101b94-4364-4019-a54d-efeb49a276d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01-LoginApplication</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>27249aeb-7d0d-4aa9-b663-2141beb3274b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC04-AccountMatching-MGA</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4ba0b513-6f0d-4348-9f65-b542b7319ba0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/MTA_PolicyNO</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4ba0b513-6f0d-4348-9f65-b542b7319ba0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PolicyNo</value>
         <variableId>7aa213af-01dc-4774-96b7-8e9d7c39244b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>952df2ad-ec4c-4db0-8918-5c2e7d363865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9805e1c8-674b-4c46-b8a2-f194b59f51d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc5574f-5e85-4757-8669-04ab6a19580d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC07-AccountMatching-Broker</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>aee23332-c179-44bd-9977-3301fdedda35</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/MTA_PolicyNO</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>aee23332-c179-44bd-9977-3301fdedda35</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PolicyNo</value>
         <variableId>64c58571-67e7-437e-b14d-21496d6750fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43eee103-f51c-49b7-a16d-fc9354890f81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7241c9ca-9617-4e94-ab0d-de032419fd7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbdd4261-f8b3-49d6-9f9c-915fc24066f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC08-AccountMatching-Insurer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a6e2352b-36c7-4735-af20-8e56d1fc3fd6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/MTA_PolicyNO</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>a6e2352b-36c7-4735-af20-8e56d1fc3fd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PolicyNo</value>
         <variableId>9c444b3f-d0a5-404e-8ee7-275bdacb4cf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d93b673-7709-4a73-b87a-02d76ead2e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>484a7b71-40a0-4bf2-9b17-fe633797eb6a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
