<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CauseOfLossC</name>
   <tag></tag>
   <elementGuidId>237cdb19-ad2e-4dd9-b23a-b93997e504f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='select2-lossCodeCause-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='select2-lossCodeCause-container']</value>
   </webElementProperties>
</WebElementEntity>
