<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ClientType</description>
   <name>ClientType</name>
   <tag></tag>
   <elementGuidId>6138b6ec-1bc3-46ab-b87a-b072aa20a588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='privateClient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='privateClient']</value>
   </webElementProperties>
</WebElementEntity>
