<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SelectPolicy</description>
   <name>SelectPolicy</name>
   <tag></tag>
   <elementGuidId>28003e70-7853-4fcf-8e5f-025c7ffe73b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='selectPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='selectPolicy']</value>
   </webElementProperties>
</WebElementEntity>
